#+TITLE: eejain.com content
#+AUTHOR: Eejain Huang
#+STARTUP: overview inlineimage
#+hugo_base_dir: ~/eejainsite/
* Front Page
:PROPERTIES:
:EXPORT_HUGO_SECTION: .
:EXPORT_FILE_NAME: _index
:EXPORT_DATE: 2020-06-15
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :bookComments false
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :bookHidden false
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :bookToC false
:END:

# {{< katex >}}\Bbb{MADE}\enspace\Bbb{BY}\enspace\color{#83A78D}\mathcal{N}\negmedspace\negmedspace\negthickspace{\forall}{{< /katex >}}

{{< katex >}}\Bbb{MADE}\enspace\Bbb{BY}\enspace\Bbb{EEJAIN}{{< /katex >}}
---

{{< columns >}}

** Who is speaking?
---
Hi there, this is Eejain.

Many tags can be attached to me: a young scholar dangling between publish or perish, a half-made geek plus self-taught scribbler,  and an enthusiast with all things quaint yet profound.

But none of them will stick.

Pared to the bone, I am just a *curious* soul that wants to share bits and pieces of thoughts with you.

file:front.jpg

# Hi there, this is Eejain.

# Many tags can be attached to me: gender-queer, born and raised Chinese, a half-made geek plus self-taught scribbler, a young scholar dangling between publish or perish, and an enthusiast with all things quaint yet profound.

# But none of them will stick.

# Pared to the bone, I am just a *curious* soul that wants to share bits and pieces of thoughts with you.

<--->

** Where is this place?
---

# This a collection of short essays on subculture, media, and human mind. They are possibly opinionated but guaranteed to be honest. And on the flip side, I avoid documenting brief passing thoughts, egocentric fantasies, and plain life events. Those writings can be better approached by using social media, personal journal, and a good old diary.

# This virtual folio starts as a serious writing practice outside academia, an earnest attempt to speak in my real voice about things that resonates with me. Things that maybe trivial and obscure, but at one point, rippled through my stream of consciousness and finds their niche.

# So it flows. [^1]

# [^1]: The symbols in the website title represent the 59th hexagram in I Ching. It's called 渙 (dispersing), depicting how wind blows water, causing dispersion and regathering in a fluid fashion. 『易經．渙卦．象曰：「風行水上，渙；先王以享于帝立廟。



This a collection of short essays on subculture, media, and human mind. They are possibly opinionated but guaranteed to be honest. And on the flip side, I avoid documenting brief passing thoughts, egocentric fantasies, and plain life events. Those writings can be better approached by using social media, personal journal, and a good old diary.

This virtual folio starts as a serious writing practice outside academia, an earnest attempt to speak in my real voice about things that resonates with me. Things that maybe trivial and obscure, but at one point, rippled through my stream of consciousness and finds their niche.

So it flows. [^1]

[^1]: The symbols in the website title represent the 59th hexagram in I Ching. It's called 渙 (dispersing), depicting how wind blows water, causing dispersion and regathering in a fluid fashion. 『易經．渙卦．象曰：「風行水上，渙；先王以享于帝立廟。
* Recent Posts
:PROPERTIES:
:EXPORT_HUGO_SECTION: posts
:EXPORT_FILE_NAME: _index
:EXPORT_DATE: 2020-06-15
:EXPORT_HUGO_WEIGHT: 1
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :bookComments false
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :bookHidden false
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :bookToC true
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :bookFlatSection false
:END:

p test

* TODO Bahn in the Dawn :@Life:Germany:ant:
:PROPERTIES:
:EXPORT_HUGO_SECTION: posts
:EXPORT_FILE_NAME: Bahn in the Dawn
:EXPORT_DATE: 2019-05-01
:EXPORT_HUGO_WEIGHT: auto
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :bookComments true
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :bookHidden true
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :bookToC true
:END:

People often talk about traveling far enough to meet one self. I would say, travel early enough serves the same purpose.
As a anxious wrecking young academic, I scratched the surface of my daily routine to find extra time for more work. It manifested as the forward marching of my wake up time. That line marker indicating start of the day currently falls at 5am.

I often take the train running at dusk, and the passengers are mostly consists of two types. news paper-reading elder gents and sleepy late night construction workers getting off work. They are often bulky guys wearing canvas pants with too many pockets. The heavy beats leaking out of their ear buds, the blotchy stains-possibly can’t be washed off-on their pants, their bear-like existence (oh the Berlin bear), separate them apart from the orderly and somewhat delicate space in Bahn. They seem to be out of place, yet so comfortable with everything. Or maybe I’m the one who’s out of place. Then I realised that I do share the city with them, me on the dayside, they on the night side. Converging only in this train, through dusk it goes.

The moment when road light switch off, from this side to the end of horizon, all of them switch off at the same time, yet no one is noticing. It’s like a massive lightning, without any sound.

The grey craw bouncing on human leftovers.

Early morning bring all forms of fantasy, not the kind of bizarre and hallucinating fantasy you would have at midnight, but bleak, sharp and unforgiving ones. It’s the gap between initiation and sustainment. What has been reached but yet to be fulfilled.

Nothing can be left aloft and unexplained, the brain is so stubborn at making sense of every thing, always ready for fight or flight. And now, in the conjunction of night and day, an island where neither the land of consciousness or sea of dreams, could control. I saw, or rather sense, workers, birds, the moon and the train.

There’s one section between park sans Lissi and golm, where the meadow always seem to be moisturised by morning dew, it’s an surreal scene with drowsy horses stretching slender limbs, every step cracks a patch of frosty grass. This creature always has dreamy eyes, but especially in early morning. Of course, they woke up with the first sunlight, when I get to see them on the train, they have already passed the human equivalent of coffee time. But still, they don’t appear active or crispy yet, they are handsome just the way it is: quiet, sentient and forgiving.

What could I say about morning. The morning is too early that feels like more of a succession than a start.

But there are experiences you can only get at early next morning. And I suggest visitors to Berlin at least keep an open mind to these dusk moments.
-
Be the first customer at that street corner bakery, count how many bottles left from the night before, take a Bahn through the woody area and see the cows and horses; hear morning chorus, according to Gordon Hampton, the natural sound scape recorder, argued that birds song are the sonic beacon of prosperity, safety for our ancestors.

my perception of bahn in the dahn took a turn after knowing elia and danniel. being the eu hippies as they are, they pointed out the hypocracy in my stubbbon habbit of sleeping at fixed schedule and waking up early. "how early could you be, can you be earlier than people who's not even sleeping yet?". after spending a night in potsdam hbf and an unplanned all-nighter at elia's house, this time i had the chance to see the city at 4am, much earlier than my previous schedule, to my surprise, the train is beyond empty. there will always be people who's earlier, and  evetually the choice of waking up early and being the first one to see everything s a dilusion of self-control. i will always be later than people who's not sleep yet.

but still, sleeping and waking at different times help me take different perspectives on the same city.

* TODO Current Podcast Favorites :@Media:podcast:ant:
:PROPERTIES:
:EXPORT_HUGO_SECTION: posts
:EXPORT_FILE_NAME: Current Podcast Favorites
:EXPORT_DATE: 2019-04-01
:EXPORT_HUGO_WEIGHT: auto
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :bookComments true
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :bookHidden true
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :bookToC true
:END:


    兼论睁着眼睛时我都在干啥

## 前言

为啥豆瓣条目不包括广播和播客的，说好的书影音全制霸呢！
–– 一个愤怒的、懒得看字的普通听众。

写在前面：
这是 2017 时的推荐： [https://www.douban.com/note/608923544/](https://www.douban.com/note/608923544/) ， 里面的推荐依然有效，曾经喜欢的播客有些已经完结，或者停播（Ctrl-Walt-Delete, Dear Sugar, Sinica），但大部分依然坚挺着，播客的黄金时代还在继续。不过我的收听习惯变了不少，作为一个播客重度用户，我只要一个人呆着基本都在听着点什么。但播客的功能已经从单一的新知获取，细化成了按照主题和长度适应各类日常活动的需要的道具，有点歌单的意思——毕竟有的播客需要全神贯注，有的只是为了听个响。所以现在我的播放清单不再按主题排序，而是按时间长短和形式了。另外播客的商业化、集中化也让 podcasting network 的概念变得重要起来，这就像。所以以下推荐会在主题关键词和形式之外把时长和广播网也加入考量。

这是一个非常私人的播客推荐清单，关键词按主题、形式和长短归纳。收听工具依然推荐使用老朋友 Overcast，但任何通用型播客客户端都没问题。 就是这样

“” /
TOPICS:/
FORMAT: /
LENGTH:   min /
NETWORK: /
HIGHLIGHTS:

## Topic: culture, literature, arts, design

“The Essay” /
TOPICS: arts, history, philosophy, science, religion and beyond /
FORMAT: narration /
LENGTH: 15 min /
NETWORK: BBC Radio /
HIGHLIGHTS: BBC邀请各行当的作者朗读自己的短文，没有讨论没有铺垫，就是朗诵，但主题包罗万象，写作水平也的确高。

“99% Invisible” /
TOPICS: arts, design, architecture /
FORMAT: interview, documentary, narration /
LENGTH: 30 min /
NETWORK: Radiotopia /
HIGHLIGHTS: 制作成熟、精良，网站也非常详实，每集都能学到点新的。

“The Ezra Klein Show” /
TOPICS: media, politics, social issues  /
FORMAT: interview  /
LENGTH:  100 min /
NETWORK: Vox Media /
HIGHLIGHTS: 一个左倾，Ezra Klein 是最早用私人博客的形式报道政治活动的左派记者之一，随和热情的风格，

## Topic: social issues, humanity, crime

## Topic: technology, internet, start-up


## Topic: food, cooking, travel


## Topic: fiction, comedy, subculture
* TODO Creating Diagram :@Academic:technology:visualization:ant:
:PROPERTIES:
:EXPORT_HUGO_SECTION: posts
:EXPORT_FILE_NAME: creating diagram
:EXPORT_DATE: 2020-10-07
:EXPORT_HUGO_WEIGHT: auto
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :bookComments true
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :bookHidden true
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :bookToC true
:END:
[[file:~/Dropbox/MarkdownNotes/MDNotes/todo.org::*check out options to create diagram][check out options to create diagram]]

* TODO How to Follow Anyone Online :technology:ant:
:PROPERTIES:
:EXPORT_HUGO_SECTION: posts
:EXPORT_FILE_NAME: how to follow
:EXPORT_DATE: 2019-05-01
:EXPORT_HUGO_WEIGHT: auto
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :bookComments true
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :bookHidden true
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :bookToC true
:END:

SCHEDULED: <2020-11-06 Fri>
- bookmark the webpage
- web feed
- light weight feed info: fraidycat (not a reader)
  [2020-11-03 Tue 13:25]
- feed generator/creator, feed aggregator, feed reader
- rss vs atom
- generator: rss hub, rss bridge
  https://news.ycombinator.com/item?id=24213682
  test: https://www.apmreports.org/
  https://github.com/RSS-Bridge/rss-bridge
  https://docs.rsshub.app/
- aggregator: https://en.wikipedia.org/wiki/Comparison_of_feed_aggregators
- reader: reeder, often embeded in aggregator

* Org R Sandbox :@Meta:@Academic:
:PROPERTIES:
:EXPORT_HUGO_SECTION: posts
:EXPORT_FILE_NAME: R Sandbox
:EXPORT_HUGO_WEIGHT: auto
:EXPORT_DATE: 2020-05-25
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :bookComments true
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :bookHidden true
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :bookToC true
:header-args:R: :session *R* :exports both :eval no-export
:END:

This post presents the workflow of interacting with R in org mode. I am mainly seeking three functions in this workflow: automatic output; persistent R session across multiple source blocks; ability to present both codes and outputs.

** Preparation
- ~org-babel~ for executing and tangling source blocks
- ~ESS~ for interacting directly with R in emacs through the inferior R process

** Instruction
- set up proper sub-tree/buffer header arguments, for this blog post I used sub-tree header arguments: ~:header-args:R: :session *R* :exports both :eval no-export~
- run ~org-bable-execute-src-block~ (or on sub-tree/buffer level) to produce outputs in the text area

** Example
*** Plot output
- For the following code block, I used the source block header arguments ~#+begin_src R :results output graphics file :file test.svg :output-dir ~/itflows/static~
- Note on the header arguments:
  + use ~:results graphics file~ when producing base R plot. use ~:results output graphics file~ for ggplot (see https://orgmode.org/worg/org-contrib/babel/languages/ob-doc-R.html).
  + remember to specify ~:output-dir~ as the static folder in your hugo directory, or else the org-link to the output plot after code evaluation will be directed to the same directory as the .org file by default

#+begin_src R :results output graphics file :file test.svg :output-dir ~/itflows/static :R-dev-args bg="transparent"
setwd('~/itflows/static') # output plot stored in the static directory of your hugo blog
library(dplyr)
library(ggplot2)
print(ggplot(iris, aes(x =  Sepal.Width, y = Sepal.Length)) +
      geom_point() +
      theme_bw()
      )
                                        # If the source code block uses grid-based R graphics, e.g., the lattice and ggplot2 packages, then care must be taken either to print() the graphics object, specify :results output, or run the code in a :session", use print() to produce proper .svg output

square <- function(x) # test session persistency
  {
    x * x
  }
#+end_src

#+RESULTS:
[[file:~/eejainsite/static/test.svg]]



#+begin_src R :file test2.svg :results graphics file :output-dir ~/itflows/static
plot(matrix(rnorm(100), ncol=2), type="h")
#+end_src

#+RESULTS:
[[file:~/eejainsite/static/test2.svg]]

# {{< embed-pdf url="/test2.pdf" >}}

*** Plain text output
- source block header arguments: ~#+begin_src R :results output~

#+begin_src R :results output
square(1:10)
#+end_src

#+RESULTS:
:  [1]   1   4   9  16  25  36  49  64  81 100

* TODO My Reference Management Workflow with Zotero :@Academic:productivity:
:PROPERTIES:
:EXPORT_HUGO_SECTION: posts
:EXPORT_FILE_NAME: my reference literature management workflow
:EXPORT_HUGO_WEIGHT: auto
:EXPORT_DATE: 2020-09-09
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :bookComments true
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :bookHidden true
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :bookToC true
:header-args: :tangle no eval: no-export :cache yes :results silent :padline no
:END:

#+include: "/Users/naskuv/Dropbox/MarkdownNotes/MDNotes/my reference literature management workflow.org" :only-contents t

* TODO A Quick Comparison between Zotero and Citavi :@Academic:productivity:
:PROPERTIES:
:EXPORT_HUGO_SECTION: posts
:EXPORT_FILE_NAME: compare zotero and citavi
:EXPORT_HUGO_WEIGHT: auto
:EXPORT_DATE: 2020-09-08
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :bookComments true
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :bookHidden true
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :bookToC true
:header-args: :tangle no eval: no-export :cache yes :results silent :padline no
:END:

#+include: "/Users/naskuv/Dropbox/MarkdownNotes/MDNotes/compare zotero and citavi.org" :only-contents t

* TODO My Academic Reading Workflow :@Academic:productivity:
:PROPERTIES:
:EXPORT_HUGO_SECTION: posts
:EXPORT_FILE_NAME: my academic reading workflow
:EXPORT_HUGO_WEIGHT: auto
:EXPORT_DATE: 2020-09-08
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :bookComments true
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :bookHidden true
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :bookToC true
:header-args: :tangle no eval: no-export :cache yes :results silent :padline no
:END:

#+include: "/Users/naskuv/Dropbox/MarkdownNotes/MDNotes/my academic reading workflow.org" :only-contents t

* TODO Notes on Citation Syntax :@Academic:productivity:
:PROPERTIES:
:EXPORT_HUGO_SECTION: posts
:EXPORT_FILE_NAME: Citation Syntax
:EXPORT_HUGO_WEIGHT: auto
:EXPORT_DATE: 2020-09-08
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :bookComments true
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :bookHidden true
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :bookToC true
:header-args: :tangle no eval: no-export :cache yes :results silent :padline no
:END:

#+include: "/Users/naskuv/Dropbox/MarkdownNotes/MDNotes/Citation Syntax.md" :only-contents t
* TODO My Doom Emacs Configuration :@Meta:technology:
:PROPERTIES:
:EXPORT_HUGO_SECTION: posts
:EXPORT_FILE_NAME: My Doom Emacs Configuration
:EXPORT_HUGO_WEIGHT: auto
:EXPORT_DATE: 2020-09-08
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :bookComments true
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :bookHidden true
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :bookToC true
:header-args: :tangle no eval: no-export :cache yes :results silent :padline no
:END:

#+caption: Emacs main window in iTerm2
file:~/itflows/static/doomsnap.png

#+caption: Emacs quickshow window with Org agenda
file:~/itflows/static/doomsnap2.png

#+include: "~/.doom.d/config.org" :only-contents t

* Planning 2020 Beyond Work-Life Balance :@Life:productivity:
:PROPERTIES:
:EXPORT_HUGO_SECTION: posts
:EXPORT_FILE_NAME: Planning 2020 Beyond Work-Life Balance
:EXPORT_DATE: 2020-01-03
:EXPORT_HUGO_WEIGHT: auto
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :bookComments true
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :bookHidden true
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :bookToC true
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :endLevel 2
:END:

** A Broken Self and a New Decade

With the tingly smell of mulled wine, the dazzling Christmas lights in Berlin streets, I found myself in a very dark place at the end of 2019: it's the end of a decade yet my life is full of loose ends. Trying so hard to be the best version of myself as an instructor, a scholar, and a creator, I had, not literally, untied shoe laces that will trip myself over nothing every single day.

I think I am not alone in this: the yearning for multitude of wonderful things  ended up as a self-paralyzing force. The world is most ravishing in your fantasies, right? Unfortunately, daydreaming stopped to be pleasant after I realized how little had I done to reach my idealized world––a place that's elegant, profound, gentle and intriguing , a world I would love to be a part of.

So I've picked up all the loose ends and started to sketch a road map to there. And this post is a record of what I have done.

** The Three-layer Structure

I would like to achieve two seemingly contradictory goals with my organization system: keep track of everything, and don't overwhelm myself. My current workaround is a system with three nesting layers and each layer requires different degree of attention and monitoring (energy!).

The outmost layer is areas of life that I would like to balance on a daily basis. These are facet of life that I would make sure to give equal, unbiased energy and resource every single day. For most people, this could be just work and life. Me personally have three areas of life (serious/leisure/misc) which I will discuss in the next section.

The mid and second layer is sub-areas of life. They are also important and requires regular attention, but not on a daily basis. For example, I have four sub-areas in **serious stuff**: publication, academic development, teaching and organization. I would cycle through all these sub-areas every week, but the time invested on each sub-area might be different from week to week.

The innermost layer are projects that are [SMART](<https://en.wikipedia.org/wiki/SMART%5Fcriteria>) (specific, measurable, achievable, relevant, time-bound). They are actionable projects that would help me reaching the vision of a particular sub-area of life. Since they are time sensitive and have clear criteria for success, I can evaluate the process easily every week and month. Next, I would like to put these three layers into context and give them some very subjective definitions.

** Identify Areas of Life

Everything I do, every second I spend and every bit of energy I consume (even in off-state, even during sleeps) is motivated by certain needs. I do **serious stuff** for professional development, financial security, social status, all of which are necessary to earn a proper position in this society. I do **leisure stuff** for enjoyment, self fulfillment and human connection. And I do **misc stuff** for living as a responsible adult that takes care of her own health, finance, possessions, legal docs etc. I used to rank serious stuff > leisure stuff > misc stuff, now I understand (after several burnouts) that they refuel each other, and should be treated equally on a daily basis.

My three areas of life may not be everyone's focus, but you can substitute anything that you deem precious and would like to keep a close eye on.

** Create Sub-areas within Areas

Using the area of life as a start point, what I did next is to write several statements to descriptive my prospect for each area. For example, I put down "I want to be a small expert in my small field" in the area of **serious stuff**, and I then formalized this vision into a sub-area called academic development. Eventually, I have four sub-areas in **serious stuff**: publication, academic development, teaching and organization; three sub-areas in **leisure stuff**: output, social, input; and two sub-areas in **misc stuff**: health (eating, skincare, workout, etc.) and chore (tax, record transaction, shopping, house cleaning, etc.). Noting that the sub-area of chore contains many elements, as they are not my focuses of life right now.

** Create Projects within sub-areas

The distinction between sub-areas and projects lies in whether they can be completed within a time frame. For example, health is a sub-area of my life that needs frequent investment, I cannot tick it off and say it's done. But I may have various projects within this sub-area that can and should be completed after certain duration of time, such as run for 5 km without stop in two months. And in order to reach this very specific goal, I can set concrete to-dos and keep track of its progress.

** How Does it Work in Real Life?

The beauty of this system lies in the differentiated energy requirement for each layer. From area to sub-area to project, the degree of flexibility increase and active monitoring decrease.

To be more specific, at the start of a week, I will decide which sub-area(s) in each of the three areas I'm going to focus every day. The priority of sub-areas is determined by importance, urgency and sometimes, guts. I will try to work on every sub-area in a week, but not everyday. For instance, I may decide to work on serious\_publication + leisure\_input + misc\_health on Monday, and change to serious\_teach + leisure\_output + misc\_chore on Tuesday, and cycle through each sub-area throughout the week. This can be evaluated by the hour I spent in to-dos for each sub-area and adjusted during weekly review. Completion of a project take time and effort, but I don't have to work on each project every day or every week, as long as it's finished within the time frame defined by the project.

Essentially, what I need to plan and monitor actively everyday is the time/energy spent on each area. I will review and plan sub-areas only once a week, and for projects, once a month.

** Does it Work?

Honestly, I don't know yet, but this system has given me clarity and a sense of purpose for the past two weeks. It is my current answer to the dilemma of wanting everything and getting burned out along the way. Noting that it is definitely not a manual or solution, but rather a record of my attempt to gather and organize the gruesome but magnificent beast which is life. And as everything in life, it's a work in progress.

I think I've learned something along the way, but there's also Rick Sanchez's voice saying “Oh boy, so you actually learned something today? What is this, Full House?”, to which I want to answer: this is my best attempt to make sense of this world. And I hope it could be useful for the anonymous readers out there as well.
