#+hugo_base_dir: ~/itflows/
#+hugo_section: docs/fic

* Fictions :toc:
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:END:

- [[#inferno-目色][Inferno 目色]]

* Inferno 目色 :@FanFic:manga:noexport_1:
:PROPERTIES:
:EXPORT_FILE_NAME: Inferno 目色
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :bookHidden true
:EXPORT_DATE: 2017-12-01
:END:
** Inferno 目色
#+begin_details
#+begin_summary
This fanfic is based on "Inferno" by Tomo Matsumoto
#+end_summary
[[google:Tomo Matsumoto]]
#+end_details

他睁开了眼睛，几声闷雷滚过，窗玻璃在狂风中振动着。室内昏暗模糊，从他躺的角度能看到迫近的积雨云，正不断变幻着形状。重重堆积的云山，像沉默又饥饿的野兽，边缘却镶着明亮的白色。听着楼下时隐时现的流水声，他突然觉得干渴难忍。

走廊挂着的时钟指向中午十二点，家中除了厨房却是一片暧昧不明。他昏昏沉沉地走向开放式厨房边上的冰箱。

这是十六岁的家入轰从九州回到东京的第一个夏天，天气灼热得史无前例。震耳欲聋的蝉鸣和雷声中，连电器运转的声音都显得有气无力。

他边抹汗边打开冰箱，里面整齐地码着可丽饼、乳酪球和草莓蛋糕。草莓是无子的，茎叶都被仔细摘去并整齐地切成两瓣，盖在白润的奶油上像是颗红心。

四年过去了，她还是记得我爱吃什么。家入轰看着草莓蛋糕心想。

她总是这样，无关紧要的细节攥得太紧，对重要的事情却一笑带过。在别人看来是恬淡寡欲，在他眼中却是骇人的天真。他永远不懂那是城府太浅还是太深。

譬如说，她总是知道他喜欢什么样的甜品。譬如说，她笑着吃掉了那块蛋糕……


「小更，我再也不要吃草莓蛋糕了。」 十一岁的家入轰一反常态地推开了眼前松软洁白的草莓蛋糕。那时的他还稚嫩清秀，被邻里戏称为小娜塔莉波特曼。

「难道你要巧克力的么，说吃了就会拉肚子的不知道是哪位啊？」 十二岁的她，眉间挑着点戏谑笑看着轰。

「说不吃就不吃，把你的巧克力蛋糕给我，我们交换！」 轰语气强硬，眼睛却一直不敢看她。

她笑着摇了摇头，把彼此的盘子交换过来。

「不过，小轰你知道么，人会渐渐变得像他吃掉的食物哦。」 她一边舔掉嘴边的奶油一边笑着说，「你看你长得像个洋娃娃一样，都是因为你喜欢吃草莓蛋糕呢。要是吃巧克力的话你知道会怎么样嘛？」

「什么啊，难道你要说我会变黑么。」 家入轰眼神有意无意地扫过她的嘴唇。她的皮肤光滑白皙得和奶油不分彼此，更衬得微笑着的唇瓣鲜艳欲滴。他看了一眼就不敢再看，视线下移到她面前放着的草莓蛋糕。

然而草莓蛋糕那柔滑的奶白上几点嫣红，更是像极了昨夜那不能为人道的绮梦。梦中有纠缠濡湿的肢体，白得像上好的乳脂，红得像玫瑰扎出的血珠。心中生出的欲望，心却不明白。家入轰脑中嗡嗡作响，手下捣着蛋糕，不觉间已是一身薄汗。

「哈哈哈，不是哦，你会变得和巧克力一样苦。」 她对轰的惊惶似乎毫无所知，随便地捏了一下轰的脸颊，仍旧笑得一派悠然。

真是乌鸦嘴啊。回忆到那天的事情，他不由苦涩得笑了。细想起来，似乎他的痛苦真的从那一刻开始了。并且随着年岁增长而越来越痛，越来越苦。

不过那之后，她的笑容并没有陪伴他很久。在家入轰弄明白心中蠢动的妄想是什么之前，二人就被分隔两地。东京和九州，坐希望号不过五小时的车程，对两个孩子来说却像天人永隔。那年家入轰十二岁。

落地窗外一个竖闪霎时打亮阴暗的客厅，雷声接踵而至，比先前的闷雷响亮不少，狂风也卷着沙尘噼里啪啦地打在玻璃上。家入轰拿着蛋糕和罐装咖啡绕过沙发，一屁股坐在了地上。他伸手打开DVD，有一搭没一搭地看起了电影。

片子是从打工处的斋藤前辈那里借的。说是借有点不对，那天斋藤一脸自以为温暖阳光的傻笑，给正在收银处发呆的自己硬塞了「包你笑到流泪」的影碟。大概是因为自己曾经不小心透露过苦恋的事实，导致这个很容易和人共情的大男孩时不时要以前辈的身份关怀一下他。「喜欢一个人是好事呀，会让人变得温柔和坚强呢。」诸如此类的斋藤语录。

温柔和坚强都是强者才能享有的特权，自己只是匍匐于欲望和绝望脚下的奴隶而已。家入轰从十二岁那年就明白了这一点。

「小轰，好好看着我。」分别的那天，她脸上带着一如既往的悠闲笑容，好像只是在送他去上学，「你要记得我的脸哦。」

「说得就好像我有脸盲一样，你的脸看了十年早就看腻了。」轰的刘海挡住了昨夜哭肿的眼睛，别过头去，直到最后也没再看她一眼。

然而她随口说的种种戏言却总是一语成籖。

刚刚迈入初中的家入轰身上糅合着微妙的青涩和超出年龄的忧郁，一张比少女更秀美的脸庞总是能轻松吸引年长的女性。在九州生活的第一个月，家入轰就糊里糊涂地被家教带上了床。

对方是个高二女生，有着顺滑的黑直长发，说话间总是摆弄着自己的头发：「小轰，你知道きがかん这个词是什么意思嘛？这可是考点哦。」

「我早就知道了，有人教过我。」

明明是在学着国语，却不知怎么就唇齿相接，继而滚上了床……

在下体的酥麻随着碾磨一层层弥漫开来时，他恍恍惚惚地看着身下的女性心想，这就是令小学男生们面红耳赤的「做爱」吗？为什么感觉欠缺了什么？这头长发应该再短一些，颜色也应该是淡一点。一瞬间，正在娇吟的女人变了个样子：将将盖住耳朵的清爽短发在光下泛着淡淡茶色，散落在指缝间勾起丝丝凉滑。肌肤薄透白润，耳廓点染着情动的淡红……随着他的想象，脸转了过来，五官精巧，对称得简直仿若人造。在一阵急似一阵的冲撞下，唇边却挂着不合时宜的悠然笑容：「小轰，不要忘了我的脸。」

……轰在攀上第一次高潮的瞬间感到了翻江倒海的恶心。眼前一片刺眼的白，耳中却依然回响着她的笑语。

「小轰，这是初一的考点，给我好好背住，在九州可不要被人比下去哦。きがかん，汉字写作‘飢餓感’，就是腹内空空难以忍受的感觉。」

没有什么开心，无法变得坚强，只有心中永远饥饿的野兽日夜叫嚣着。兽吃掉了小娜塔莉波特曼的外皮，吃掉了童年对她单纯的依恋，骨骼拔节生长，那个欲望终于破壳而出。他更加地饥饿了。

草莓蛋糕不知道在冰箱里放了多久，奶油带着若有若无的酸味。按她的性格，一定是刚听说他要回来就去买了吧，一刻都不会耽搁。而又是因为她的性子，就算他没有吃蛋糕，她也一定不会扔掉它，直到坏得不能再坏了为止，直到整个冰箱也被腐败占据。即使如此，最终他还是拿出了蛋糕，一口不落地吞咽下去。

家入轰感到了久违的反胃。

屏幕上六个身穿警服的英国男人正随着音乐一边扭动一边脱去衣服，挺着肚腩、光着屁股的形象很是滑稽。不过身份错位所营造的滑稽感离恶心不过一步之遥。明明是喜剧，他眉间却一直打着疙瘩。

水声停了。「你在看电影吗？」

随着平稳轻松的问话，是突然接近的温度，和视野边缘散发着诱人光彩的白。她结束了厨房的劳作，擦了手挨着轰在沙发坐下。云层压得愈发低了，空气中像带了静电一样，凝滞而满布危险的吸引力。他只感觉闷热得喘不过气，汗水顺着陡峭的下颌线滚落，啪嗒。

「是啊，从斋藤君那里借来的。」 他目不斜视，好像完全被屏幕上光着屁股的男人吸引了，然而脸上一丝波动也无。

「交到朋友了呢，真好，我原本还担心你会不会在超市和人打起来。」 她仰了头看轰。四年过去，现在的她就算坐在沙发上也需要抬起头才能看到轰的脸。

「说得我好像失足青年一样。」

「难道不是吗，你现在就是一身大型猫科动物的气场，这么低气压真的没有顾客投诉？啊，说起来你打工是有什么东西想买吗？难道是机车？」 她就像一个好姐姐一样，在轻松的打趣中夹着关心。

然而这回他没有答话。如果不是知道母亲已经告诉了她自己打工的原因，那么他大概还可以继续装下去。 继续扮演一个略显桀骜叛逆，但骨子里还是普通高一少年的角色。就好像一切阴暗不过是惺惺作态。

他打工的原因很简单，他需要钱离开这个家，离开这个令他深陷炼狱的女人。

又一声炸雷，雨终于倾盆而下，室内令人窒息的沉默被无处可逃的雨声打破。

「啊这个画面看起来好眼熟，电影叫什么名字？」 从轰脸上移开视线，她就像什么也没发生一样挑起了新的话题。

又来了，那种可怕的天真和淡然交织的情态。

「The Full Monty」

「我听说过，好像是经典喜剧？没想到你会特意借这种片子看呢。」 她扫了一眼坐在地上全身戒备着的少年，又向他挪近了些，「我还以为你的事情我全部都知道得很清楚呢。」

被她清甜的气息笼罩，轰的眼神不由自主地掠过她裸露在外的肌肤，但又小心翼翼不让彼此眼神交汇。因为闷热的缘故她只穿了一件吊带背心，脖颈、肩膀、手臂……全部都很精巧，自己单手就可以抓住那双纤弱的手腕吧，想要粗暴得撕咬那透明的皮肤，就这样一口气用自己的白色玷污那无垢的白会怎么样？轰的妄想突然一拥而上，饥饿的目光如有实体。

然而他的目光最终停在她纤细的锁骨上，白皙的肌肤起伏中围出一汪阴影，那里卧着一条细致的金色项链，三个小小的十字架嵌在其中。那是他上周送给她的生日礼物。

​	_一个兽从炼狱中上来，有两角如同羔羊，说话好像龙。_

​	_它的贪婪欲望从来不会得到满足， 它在饱餐后会感到比在饱餐前更加饥肠辘辘。_

能佑护她免被兽亵渎的只有神的印记。

「你又知道什么。」回过神的轰终于直视了她的眼睛。脑袋清醒后，一股无名怒气陡然升起。

你能舍弃一切回应我的欲望么？你能和我一起堕入地狱么？我那么努力地戴上伤人伤己的面具，和你保持距离，你却……

「你根本不知道自己在做什么，什么都不知道。」

玻璃上成股流下的雨水，无声地哭泣着。



三年多没见的母亲还是一样酒肉不禁，豪放地在大中午就放开肚皮喝啤酒。飞快成长的少年早就超过了母亲两个头，但是面对这个自由自在的女人时轰还是很敬畏。在学校里成绩优秀、体育全能的家入轰是个很自律的国三学生，身上黑色的中山领制服严谨地系到了最上面一颗扣子。

母亲一口撸下鸡皮串，一边看着自己的小儿子，笑道：「我的小公主现在真是仪表堂堂，但是这么严肃一点都不好玩，你现在也不会动不动就哭鼻子了吧？」

「妈，我现在可是篮球队的主力，别瞎操心了。你这次来九州不会就是为了吃烤串吧？」

「不不，我是为了博多明太子酱来的。」母亲一本正经地说。

「我才不信。」

「唉，孩子大了真不好逗，家里的那个也是一样。啊不过，她一向都是一副笑面虎的样子，天知道在想什么。你知道吗她在学校被人取了外号叫圣女呢哈哈哈！」摇头晃脑的母亲又干了一大口。

轰在桌面下攥起了拳头。

「好了好了，我说实话吧，其实我和你爸要复婚了。挺不好意思的，老这么折腾你们……所以你高中就来东京上吧。”母亲笑嘻嘻的，一点都不像不好意思的样子。「哎呀，九州的烧鸟果然一绝，要是啤酒能再给劲点就完美了。我给你讲，烧鸟还是要刷蒲烧汁才好，那些只刷味啉的都是邪道。」

后面的话轰一句都没听到，他像是被闷头几棍，棍棍打中要害，他感到心脏被紧紧攥住，肺叶压缩到极限，大口喘气时眼前一片昏花。

为什么？为什么？明明在不能向任何人倾诉的欲念中煎熬了不知多久，终于怀着向死的决心，烧去了和她有关的一切，满身疮痍地逃离了她的幻影。好不容易压制了饥饿的野兽，为什么现在却要重新被玩弄于股掌之间？

家入轰听到了业火劈啪作响的声音。欲海邪山向他倾坠而来。

「果然家人能够团聚真好呀，小轰你一定很高兴吧？诶你该不是高兴到哭出来了吧？」 母亲又解决了两串烧鸟，完全没察觉儿子身上发生了什么。

「……是啊，我很幸福。」 轰把脸深深埋进了掌心。

这个世界充满了幸福，从高久轰变回了家入轰的他，在这一团喜乐中开始痛哭。

悲伤吗，恐惧吗，恶心吗，绝望吗，

快活吗，安心吗，满足吗，渴望吗？

更，小更，家入更。我那血脉相连的姐姐。

家入轰在铺天盖地的雨声中闭上了眼睛，她的白色持续灼烧着他的视网膜。



* TODO Inferno 目色 pt.2 :@FanFic:manga:noexport:
:PROPERTIES:
:EXPORT_FILE_NAME: Inferno 目色 pt.2
:EXPORT_DATE: 2016-08-01
:END:




家入轰垂眉敛目，眼观鼻，鼻观心，心知这重眼帘不能拉开，抬眼即是万劫。



自杀者和不自杀者，杀人者和不杀人者，乱伦者和不乱伦者，有什么本质区别吗？没有，因为在杀人、自杀、乱伦之前他们都曾是不杀人、不自杀、不乱伦之人。而人不会在瞬间产生质变。用某种行为来定义人是最没有区分度的分类方式。

如果你说乱伦之人是有罪的，那么他的罪是从什么时候开始的？从一个绮念，一个轻吻，一场床事，还是一个眼神？





对视超过四分钟，我们就会相爱。


就像对姐姐抱持着欲望的青春期弟弟一样。



撒娇的弟弟，惹人怜爱的弟弟，需要陪伴的弟弟，在她心目中我也不过是这种存在吧。这种施舍的温情我再也不需要了。





如果不是弟弟就好了，那么我们的拥抱一定会被原谅吧。



- 童年

家入家有一对姐弟，铁打不动的微笑圣女，和梨花带雨的洋娃娃，而前者通常都是后者哭泣的原因。

最喜欢吃甜甜的草莓蛋糕的弟弟，只有一次选了漆黑的巧克力蛋糕。
眼中泛起的水光马上就要盛不住了，却控制住了声音的颤抖，「姐，我要你手上的，巧克力蛋糕。」。

那样一心望向自己，眼中盛满泪水的弟弟，真是可爱啊。可爱得家入更百爪挠心，痒中带痛。
只要弟弟一哭，家入更就紧赶着把一切奉上，但是隐隐得又是希望能看到弟弟的泪水。

父母决定离婚，向两人摊牌的那一晚，

家入更站在轰的门外，听了一会屋内上气不接下气的哭声，没有敲门，直接推门走了进去。

「小轰，我们一起离家出走吧。」

抽抽搭搭立刻被倒吸气的声音代替，家入轰通红着眼睛抬头看姐姐，而家入更依然是雷打不动的微笑。

轰看得愣愣的，突然来了一句，「更……我从来没见你哭过，这不公平。」

「我看到你哭的时候就想笑，那还怎么能哭得出来呢？」

家入更没有说出的是：每当看到你哭，我就一心只想把你的泪水一滴不落地占为己有，看得着迷，反而忘记自己的伤心了。

十二岁的少年和十三岁的少女又能走到哪里去呢？


家入轰哭的时候立刻变回了小孩子，眼睛湿润而软弱。


这是不智的决定，基于腐坏的道德，未来不可掌握，身后也毫无退路。

家入更不止一次得心想。

我无法确定的是，这其中有没有荷尔蒙爆裂出的幻想，有没有对禁忌的饮鸩止渴？如果你不是弟弟那么我们会相爱么？

- 再会

夕阳行将落下，在家入更的身前拉出一道狭长的影子。
「没关系，我们俩最喜欢黏在一起聊天了...」 家入更一边说着一边在书包中翻找着家门钥匙。
身前的影子突然蔓延开来。一个男孩，不，男人悄无声息地侧身贴近家入更，遮住了最后一点阳光。鼻尖嗅到了淡淡的麝香味，混杂着青草和一点橡胶的气息。家入更浑身的汗毛不受控制得立了起来。
男人骨节明显的手指将钥匙插进锁孔，在打开门紧接着关上的间隙里居高临下地扫了家入更一眼。

那个像女孩子一样柔弱又温和的弟弟去了哪里？像是一道道轰然的雷电炸响的间隙，那带着静电的空气，令人头皮发麻的危险吸引力。又像是懒懒地舔舐着利爪，却随时准备一口封喉的野兽。

- 爱无能

圣女家入更是有缺陷的，简单来说就是无法对人抱有恋爱的感情。被奉上神坛的好处在于，男性是不会轻易追求和自己等级相差太多的女性的。在等级排位中，家入更就是「最高级」的直接定义。也就是说，只可远观不可亵玩。
「你看，谈恋爱这回事再怎么高尚也有互舔伤口的意思在里面吧，或者说是填补空缺。但是家入更已经是个完成品了，所以她可以爱上任何人。」
「，因此也不会爱任何人么」

家入更身上缺少某种必要的激情。什么都感觉不到，吉永君的快乐也是，痛苦也是，看得清形状却感受不到，明明是那样开心见到你，我感到很羞愧。

在狭小的卧室里，浓烈的气息腾腾升起，野兽的厉齿已经磨上了我的颈动脉，下一秒就要撕裂血管，但为什么，我一点都不感到恐惧呢？大概，我一直在等待这双炽热眼睛的主人。把自己变作牢笼也要关住的，这头野兽。而能与兽共舞的，也只能是兽吧。

- 现在

「现在我就是‘兴趣爱好：家入更’的状态嘛，这我也没办法呀。」
「‘现在’呢，肯定很快就会厌烦了吧。」
家入更冷淡得别过脸去。过去、现在、未来，只有「现在」是完全的幻觉，没有比现在更不重要的了。沙与水之间从来也没有分界线，沙就是沙，水就是水。


重心微微向左

幸好是弟弟，就算你对我的迷恋消散，我们也会永远在一起。

因为你是我的，弟弟，是我的啊。













激烈的鼓点渐渐隐去，曲子跳到了下一首，“Open Road”。
“Yellowjackets 的Jazz Fusion，是你喜欢的风格吧？”家入更闭着眼睛边听边问
“无拘无束又丰满复杂的感觉我很喜欢，不过更学姐怎么会知道？” 古庄
“更学姐，更，我是真的很喜欢你”
更半晌没说话，待三分多钟的曲子结束才睁开眼睛看着古庄。
“我知道的，谢谢你。我们真的很合适不是么？” 更的眼中含笑，真挚地说道。
“古庄君，从今以后，你要的我都会给你。”
是的，只要能换得这颗心的自由，我什么都可以给你。更的眼睛闪闪发亮。

“你和那个蜥蜴眼真的好吵。不知道这个家的墙壁很薄么？”
“轰，接下来的三分三十七秒你有什么计划？”更没有揭穿轰装睡的事实，
“什么？没有啊。为什么问这个？” 轰皱了眉头
更什么也没说，直接倾身吻住了轰，缓缓碾转。
轰在一瞬的惊诧后闭上了眼睛。这是一个悠长得过分的吻。三分三十七秒，一秒不少，一秒不多。

大雨倾盆而下，雷声撼动更的心脏以更快的速率跳动起来。有热度开始蔓延。

古庄的审美一向纤细，他辨出更身上散发出香柠檬和茉莉混合的香味，更辨出这带着点勾人的印度檀香后调的香气，和轰身上的味道几无二致。

一息间，轰的脑中循环了诸多话语，但是随着风声飘远，再也没有回到嘴边。

人和人间的羁绊其实是限量拥有的，血缘关系、国仇家恨、情情爱爱，在彼此身上只能得到一种，再多就会崩坏。

- 离异四年，小一岁，再见面是一个高二（17）一个高一（16），所以离开时13和12
- 父母都爱加班，
- 轰是B型血
- 高久轰
- 轰初中在九州，现在是东京
- 大得不像话，粗暴状，
- 学生会团子头：武田慧理
- 打工处的前辈：斋藤君
- 追更的轻浮男：日村亚莲
- 喜欢轰的：玲奈（丰子）
- 家入更被前任学生会长表白过
- 更初二时喜欢的：吉永君，最喜欢的吉永君明明发生了这种事情，我却什么也感受不到，活着，对一切无感，直到死去
- 平田俊子的诗集
- 古庄君，高一，摩羯座，初中是吹奏部，本来是想吹萨克斯最后变成了中提琴，大阪人，妈妈很粗野
- 京都俵屋旅馆的香皂，香柠檬和玫瑰，印度檀香，茉莉混合的味道


只属于我一个人的恋情在四年的长度上展开
