#+hugo_base_dir: ~/itflows/
#+hugo_section: docs/nonfic

* Nonfictions :toc:
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: bookComments false
:END:

:END:














* TODO Good :@germany:noexport:
:PROPERTIES:
:EXPORT_FILE_NAME: Good
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :bookHidden true
:EXPORT_DATE: 2019-05-01
:END:

People often talking about traveling far enough to meet one self. I would say travel early enough serves the same purpose.
As a anxious wrecking young academic, I screened

I often take the train running at dusk, and the passengers are mostly consists of two types. news paper-reading elder gents and sleepy late night construction workers getting off work. They are often bulky guys wearing canvas pants with too many pockets. The heavy beats leaking out of their ear buds, the blotchy stains-possibly can’t be washed off-on their pants, their bear-like existence (oh the Berlin bear), separate them apart from the orderly and somewhat delicate space in Bahn. They seem to be out of place, yet so comfortable with everything. Or maybe I’m the one who’s out of place. Then I realised that I do share the city with them, me on the dayside, they on the night side. Converging only in this train, through dusk it goes.

The moment when road light switch off, from this side to the end of horizon, all of them switch off at the same time, yet no one is noticing. It’s like a massive lightning, without any sound.

The grey craw bouncing on human belongings

Early morning bring all forms of fantasy, not the kind of bizarre and hallucinating fantasy you would have at midnight, but bleak, sharp and unforgiving ones. It’s the gap between initiation and sustainment. What has been accomplished but yet to be fulfilled.

Nothing can be left aloft and unexplained, the brain is so stubborn at making sense of every thing, always ready for fight or flight. And now, in the conjunction of night and day, an island where neither the land of consciousness or sea of dreams, could control. I saw, or rather sense, workers, birds, the moon and the train.

There’s one section between park sans Lissi and golm, where the meadow always seem to be moisturised by morning dew, it’s an unrealistic scene with drowsy horses stretching slender limbs, every step cracks one dusty grass. This creature always has dreamy eyes, but especially in early morning. Of course, they woke up with the first sunlight, when I get to see them on the train, they have already passed the human equivalent of coffee time. But still, they don’t appear active or crispy yet, they are handsome just the way it is: quiet, sentient and forgiving.

What could I say about morning. The morning is too early that feels like more of a succession than a start.

But there are experiences you can only get at early next morning. And I suggest visitors to Berlin at least keep an open mind to these dusk moments.

Be the first customer at that street corner bakery, count how many bottles left from the night before, take a Bahn through the woody area and see the cows and horses; hear morning chorus, according to Gordon Hampton, the natural sound scape recorder, argued that birds song are the sonic beacon of prosperity, safety for our ancestors.
