#+hugo_base_dir: ~/itflows/
#+hugo_section: posts

* Hugo Org Sandbox :@Meta:development:
:PROPERTIES:
:EXPORT_FILE_NAME: Hugo Org Sandbox
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :bookHidden true
:EXPORT_date: 2020-04-10
:END:

** Basic formatting
- list item
- [ ] checkbox item
1. numbered item


 regular main text, *bold*, /italic/, _underlined_, =verbatim=, ~code~,
  +strike-through+

** Paragraphs
#+begin_verse
Great clouds overhead
Tiny black birds rise and fail
Snow covers Emacs

       --- AlexSchroeder
#+end_verse

#+BEGIN_QUOTE
Everything should be made as simple as possible,
but not any simpler ---ALbert Einstein
#+END_QUOTE

#+BEGIN_CENTER
A fog sinks in, \\
and it overlays the death.
#+END_CENTER

** Math symbols
 X^{2}, X_{2}

inline katex expression: {{< katex >}}\angle\alef{{< /katex >}}

{{< katex display >}}
\begin{array}{cc}
a & b \\c & d
\end{array}
{{< /katex >}}

note: ox-hugo sometimes render extra \

** R block
#+BEGIN_SRC R :session R
getwd()
#+END_SRC
** Table
*** simple table
| h1 | h2 |
| a  | b  |
*** three line table
|----+----+----|
| h1 | h2 | h3 |
|----+----+----|
| a  | b  | c  |
| d  | e  | f  |
|----+----+----|
** Link
[[http://www.gnu.org][test link description]]
** References
* Planning 2020: Beyond Work-Life Balance :productivity:
:PROPERTIES:
:EXPORT_FILE_NAME: Planning 2020: Beyond Work-Life Balance
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :bookHidden true
:EXPORT_DATE: 2020-01-03
:END:

** A Broken Self and a New Decade

With the tingly smell of mulled wine, the dazzling Christmas lights in Berlin streets, I found myself in a very dark place at the end of 2019: it's the end of a decade yet my life is full of loose ends. Trying so hard to be the best version of myself as an instructor, a scholar, and a creator, I had, not literally, untied shoe laces that will trip myself over nothing every single day.

I think I am not alone in this: the yearning for multitude of wonderful things  ended up as a self-paralyzing force. The world is most ravishing in your fantasies, right? Unfortunately, daydreaming stopped to be pleasant after I realized how little had I done to reach my idealized world––a place that's elegant, profound, gentle and intriguing , a world I would love to be a part of.

So I've picked up all the loose ends and started to sketch a road map to there. And this post is a record of what I have done.


** The Three-Layer Structure

I would like to achieve two seemingly contradictory goals with my organization system: keep track of everything, and don't overwhelm myself. My current workaround is a system with three nesting layers and each layer requires different degree of attention and monitoring (energy!).

The outmost layer is areas of life that I would like to balance on a daily basis. These are facet of life that I would make sure to give equal, unbiased energy and resource every single day. For most people, this could be just work and life. Me personally have three areas of life (serious/leisure/misc) which I will discuss in the next section.

The mid and second layer is sub-areas of life. They are also important and requires regular attention, but not on a daily basis. For example, I have four sub-areas in **serious stuff**: publication, academic development, teaching and organization. I would cycle through all these sub-areas every week, but the time invested on each sub-area might be different from week to week.

The innermost layer are projects that are [SMART](<https://en.wikipedia.org/wiki/SMART%5Fcriteria>) (specific, measurable, achievable, relevant, time-bound). They are actionable projects that would help me reaching the vision of a particular sub-area of life. Since they are time sensitive and have clear criteria for success, I can evaluate the process easily every week and month. Next, I would like to put these three layers into context and give them some very subjective definitions.


** Identify Areas of Life

Everything I do, every second I spend and every bit of energy I consume (even in off-state, even during sleeps) is motivated by certain needs. I do **serious stuff** for professional development, financial security, social status, all of which are necessary to earn a proper position in this society. I do **leisure stuff** for enjoyment, self fulfillment and human connection. And I do **misc stuff** for living as a responsible adult that takes care of her own health, finance, possessions, legal docs etc. I used to rank serious stuff > leisure stuff > misc stuff, now I understand (after several burnouts) that they refuel each other, and should be treated equally on a daily basis.

My three areas of life may not be everyone's focus, but you can substitute anything that you deem precious and would like to keep a close eye on.


** Create sub-areas within Areas

Using the area of life as a start point, what I did next is to write several statements to descriptive my prospect for each area. For example, I put down "I want to be a small expert in my small field" in the area of **serious stuff**, and I then formalized this vision into a sub-area called academic development. Eventually, I have four sub-areas in **serious stuff**: publication, academic development, teaching and organization; three sub-areas in **leisure stuff**: output, social, input; and two sub-areas in **misc stuff**: health (eating, skincare, workout, etc.) and chore (tax, record transaction, shopping, house cleaning, etc.). Noting that the sub-area of chore contains many elements, as they are not my focuses of life right now.


** Create Projects within sub-areas

The distinction between sub-areas and projects lies in whether they can be completed within a time frame. For example, health is a sub-area of my life that needs frequent investment, I cannot tick it off and say it's done. But I may have various projects within this sub-area that can and should be completed after certain duration of time, such as run for 5 km without stop in two months. And in order to reach this very specific goal, I can set concrete to-dos and keep track of its progress.


** How Does It Work in Real Life?

The beauty of this system lies in the differentiated energy requirement for each layer. From area to sub-area to project, the degree of flexibility increase and active monitoring decrease.

To be more specific, at the start of a week, I will decide which sub-area(s) in each of the three areas I'm going to focus every day. The priority of sub-areas is determined by importance, urgency and sometimes, guts. I will try to work on every sub-area in a week, but not everyday. For instance, I may decide to work on serious\_publication + leisure\_input + misc\_health on Monday, and change to serious\_teach + leisure\_output + misc\_chore on Tuesday, and cycle through each sub-area throughout the week. This can be evaluated by the hour I spent in to-dos for each sub-area and adjusted during weekly review. Completion of a project take time and effort, but I don't have to work on each project every day or every week, as long as it's finished within the time frame defined by the project.

Essentially, what I need to plan and monitor actively everyday is the time/energy spent on each area. I will review and plan sub-areas only once a week, and for projects, once a month.


** Does It Work?

Honestly, I don't know yet, but this system has given me clarity and a sense of purpose for the past two weeks. It is my current answer to the dilemma of wanting everything and getting burned out along the way. Noting that it is definitely not a manual or solution, but rather a record of my attempt to gather and organize the gruesome but magnificent beast which is life. And as everything in life, it's a work in progress.

I think I've learned something along the way, but there's also Rick Sanchez's voice saying “Oh boy, so you actually learned something today? What is this, Full House?”, to which I want to answer: this is my best attempt to make sense of this world. And I hope it could be useful for the anonymous readers out there as well.

